apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  # contains application secrets. DATABASE_URL points to the Postgres service created in k8s.
type: Opaque
data:
  # Replace the host below if you change the Postgres Service name
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmFkbWluMTIzQGRyb3BtYXRlLXBvc3RncmVzOjU0MzIvZHJvcG1hdGU=
  JWT_SECRET: c3VwZXJzZWNyZXQ=
