apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  # contains credentials used to initialize the Postgres container
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4xMjM=
  POSTGRES_DB: ZHJvcG1hdGU=
